package net.gallery.db;

import java.util.Date;

import oracle.sql.DATE;

public class GalleryOrderBean {
	private int GALLERY_ORDER_NUM;
	private String GALLERY_DESIGNER_ID;
	private int GALLERY_CUSTOM_NUM;
	private int GALLERY_NUM;
	private int GALLERY_ORDER_CUSTOM1;
	private int GALLERY_ORDER_CUSTOM2;
	private String GALLERY_ORDER_CUSTOM3;
	private int GALLERY_ORDER_CUSTOM4;
	private int GALLERY_ORDER_CUSTOM5;
	private int GALLERY_ORDER_CUSTOM6;
	private int GALLERY_ORDER_CUSTOM7;
	private int GALLERY_ORDER_CUSTOM8;
	private int GALLERY_ORDER_CUSTOM9; 
	private int GALLERY_ORDER_CUSTOM10;
	private int GALLERY_ORDER_CUSTOM11;
	private String GALLERY_ORDER_CUSTOM12;
	private String GALLERY_ORDER_CUSTOM13;
	private String GALLERY_ORDER_ID;
	private String GALLERY_ORDER_NAME;
	private int GALLERY_ORDER_ZIPCODE1;
	private int GALLERY_ORDER_ZIPCODE2;
	private String GALLERY_ORDER_ADDR1;
	private String GALLERY_ORDER_ADDR2;
	private int GALLERY_ORDER_PHONE;
	private int GALLERY_ORDER_MOBILE;
	private String GALLERY_ORDER_MEMO;
	private String GALLERY_ORDER_TRADE_TYPE;
	private Date GALLERY_ORDER_TRADE_DATE;
	private int GALLERY_ORDER_TRADE_PAYER;
	
	
	
	//get
	public int getGALLERY_ORDER_NUM() {
		return GALLERY_ORDER_NUM;
	}
	public String getGALLERY_DESIGNER_ID() {
		return GALLERY_DESIGNER_ID;
	}
	public int getGALLERY_CUSTOM_NUM() {
		return GALLERY_CUSTOM_NUM;
	}
	public int getGALLERY_NUM() {
		return GALLERY_NUM;
	}
	public int getGALLERY_ORDER_CUSTOM1() {
		return GALLERY_ORDER_CUSTOM1;
	}
	public int getGALLERY_ORDER_CUSTOM2() {
		return GALLERY_ORDER_CUSTOM2;
	}
	public String getGALLERY_ORDER_CUSTOM3() {
		return GALLERY_ORDER_CUSTOM3;
	}
	public int getGALLERY_ORDER_CUSTOM4() {
		return GALLERY_ORDER_CUSTOM4;
	}
	public int getGALLERY_ORDER_CUSTOM5() {
		return GALLERY_ORDER_CUSTOM5;
	}
	public int getGALLERY_ORDER_CUSTOM6() {
		return GALLERY_ORDER_CUSTOM6;
	}
	public int getGALLERY_ORDER_CUSTOM7() {
		return GALLERY_ORDER_CUSTOM7;
	}
	public int getGALLERY_ORDER_CUSTOM8() {
		return GALLERY_ORDER_CUSTOM8;
	}
	public int getGALLERY_ORDER_CUSTOM9() {
		return GALLERY_ORDER_CUSTOM9;
	}
	public int getGALLERY_ORDER_CUSTOM10() {
		return GALLERY_ORDER_CUSTOM10;
	}
	public int getGALLERY_ORDER_CUSTOM11() {
		return GALLERY_ORDER_CUSTOM11;
	}
	public String getGALLERY_ORDER_CUSTOM12() {
		return GALLERY_ORDER_CUSTOM12;
	}
	public String getGALLERY_ORDER_CUSTOM13() {
		return GALLERY_ORDER_CUSTOM13;
	}
	public String getGALLERY_ORDER_ID() {
		return GALLERY_ORDER_ID;
	}
	public String getGALLERY_ORDER_NAME() {
		return GALLERY_ORDER_NAME;
	}
	public int getGALLERY_ORDER_ZIPCODE1() {
		return GALLERY_ORDER_ZIPCODE1;
	}
	public int getGALLERY_ORDER_ZIPCODE2() {
		return GALLERY_ORDER_ZIPCODE2;
	}
	public String getGALLERY_ORDER_ADDR1() {
		return GALLERY_ORDER_ADDR1;
	}
	public String getGALLERY_ORDER_ADDR2() {
		return GALLERY_ORDER_ADDR2;
	}
	public int getGALLERY_ORDER_PHONE() {
		return GALLERY_ORDER_PHONE;
	}
	public int getGALLERY_ORDER_MOBILE() {
		return GALLERY_ORDER_MOBILE;
	}
	public String getGALLERY_ORDER_MEMO() {
		return GALLERY_ORDER_MEMO;
	}
	public String getGALLERY_ORDER_TRADE_TYPE() {
		return GALLERY_ORDER_TRADE_TYPE;
	}
	public Date getGALLERY_ORDER_TRADE_DATE() {
		return GALLERY_ORDER_TRADE_DATE;
	}
	public int getGALLERY_ORDER_TRADE_PAYER() {
		return GALLERY_ORDER_TRADE_PAYER;
	}
	
	
	
	
	//set
	public void setGALLERY_ORDER_NUM(int gALLERY_ORDER_NUM) {
		GALLERY_ORDER_NUM = gALLERY_ORDER_NUM;
	}
	public void setGALLERY_DESIGNER_ID(String gALLERY_DESIGNER_ID) {
		GALLERY_DESIGNER_ID = gALLERY_DESIGNER_ID;
	}
	public void setGALLERY_CUSTOM_NUM(int gALLERY_CUSTOM_NUM) {
		GALLERY_CUSTOM_NUM = gALLERY_CUSTOM_NUM;
	}
	public void setGALLERY_NUM(int gALLERY_NUM) {
		GALLERY_NUM = gALLERY_NUM;
	}
	public void setGALLERY_ORDER_CUSTOM1(int gALLERY_ORDER_CUSTOM1) {
		GALLERY_ORDER_CUSTOM1 = gALLERY_ORDER_CUSTOM1;
	}
	public void setGALLERY_ORDER_CUSTOM2(int gALLERY_ORDER_CUSTOM2) {
		GALLERY_ORDER_CUSTOM2 = gALLERY_ORDER_CUSTOM2;
	}
	public void setGALLERY_ORDER_CUSTOM3(String gALLERY_ORDER_CUSTOM3) {
		GALLERY_ORDER_CUSTOM3 = gALLERY_ORDER_CUSTOM3;
	}
	public void setGALLERY_ORDER_CUSTOM4(int gALLERY_ORDER_CUSTOM4) {
		GALLERY_ORDER_CUSTOM4 = gALLERY_ORDER_CUSTOM4;
	}
	public void setGALLERY_ORDER_CUSTOM5(int gALLERY_ORDER_CUSTOM5) {
		GALLERY_ORDER_CUSTOM5 = gALLERY_ORDER_CUSTOM5;
	}
	public void setGALLERY_ORDER_CUSTOM6(int gALLERY_ORDER_CUSTOM6) {
		GALLERY_ORDER_CUSTOM6 = gALLERY_ORDER_CUSTOM6;
	}
	public void setGALLERY_ORDER_CUSTOM7(int gALLERY_ORDER_CUSTOM7) {
		GALLERY_ORDER_CUSTOM7 = gALLERY_ORDER_CUSTOM7;
	}
	public void setGALLERY_ORDER_CUSTOM8(int gALLERY_ORDER_CUSTOM8) {
		GALLERY_ORDER_CUSTOM8 = gALLERY_ORDER_CUSTOM8;
	}
	public void setGALLERY_ORDER_CUSTOM9(int gALLERY_ORDER_CUSTOM9) {
		GALLERY_ORDER_CUSTOM9 = gALLERY_ORDER_CUSTOM9;
	}
	public void setGALLERY_ORDER_CUSTOM10(int gALLERY_ORDER_CUSTOM10) {
		GALLERY_ORDER_CUSTOM10 = gALLERY_ORDER_CUSTOM10;
	}
	public void setGALLERY_ORDER_CUSTOM11(int gALLERY_ORDER_CUSTOM11) {
		GALLERY_ORDER_CUSTOM11 = gALLERY_ORDER_CUSTOM11;
	}
	public void setGALLERY_ORDER_CUSTOM12(String gALLERY_ORDER_CUSTOM12) {
		GALLERY_ORDER_CUSTOM12 = gALLERY_ORDER_CUSTOM12;
	}
	public void setGALLERY_ORDER_CUSTOM13(String gALLERY_ORDER_CUSTOM13) {
		GALLERY_ORDER_CUSTOM13 = gALLERY_ORDER_CUSTOM13;
	}
	public void setGALLERY_ORDER_ID(String gALLERY_ORDER_ID) {
		GALLERY_ORDER_ID = gALLERY_ORDER_ID;
	}
	public void setGALLERY_ORDER_NAME(String gALLERY_ORDER_NAME) {
		GALLERY_ORDER_NAME = gALLERY_ORDER_NAME;
	}
	public void setGALLERY_ORDER_ZIPCODE1(int gALLERY_ORDER_ZIPCODE1) {
		GALLERY_ORDER_ZIPCODE1 = gALLERY_ORDER_ZIPCODE1;
	}
	public void setGALLERY_ORDER_ZIPCODE2(int gALLERY_ORDER_ZIPCODE2) {
		GALLERY_ORDER_ZIPCODE2 = gALLERY_ORDER_ZIPCODE2;
	}
	public void setGALLERY_ORDER_ADDR1(String gALLERY_ORDER_ADDR1) {
		GALLERY_ORDER_ADDR1 = gALLERY_ORDER_ADDR1;
	}
	public void setGALLERY_ORDER_ADDR2(String gALLERY_ORDER_ADDR2) {
		GALLERY_ORDER_ADDR2 = gALLERY_ORDER_ADDR2;
	}
	public void setGALLERY_ORDER_PHONE(int gALLERY_ORDER_PHONE) {
		GALLERY_ORDER_PHONE = gALLERY_ORDER_PHONE;
	}
	public void setGALLERY_ORDER_MOBILE(int gALLERY_ORDER_MOBILE) {
		GALLERY_ORDER_MOBILE = gALLERY_ORDER_MOBILE;
	}
	public void setGALLERY_ORDER_MEMO(String gALLERY_ORDER_MEMO) {
		GALLERY_ORDER_MEMO = gALLERY_ORDER_MEMO;
	}
	public void setGALLERY_ORDER_TRADE_TYPE(String gALLERY_ORDER_TRADE_TYPE) {
		GALLERY_ORDER_TRADE_TYPE = gALLERY_ORDER_TRADE_TYPE;
	}
	public void setGALLERY_ORDER_TRADE_DATE(Date date) {
		GALLERY_ORDER_TRADE_DATE = date;
	}
	public void setGALLERY_ORDER_TRADE_PAYER(int gALLERY_ORDER_TRADE_PAYER) {
		GALLERY_ORDER_TRADE_PAYER = gALLERY_ORDER_TRADE_PAYER;
	}
	
	
	
	
	
}
